//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Service.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class FoodLoverContainer : DbContext
    {
        public FoodLoverContainer()
            : base("name=FoodLoverContainer")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<NguoiDung> NguoiDung { get; set; }
        public DbSet<MonAn> MonAn { get; set; }
        public DbSet<BinhLuan> BinhLuan { get; set; }
        public DbSet<MucDo> MucDo { get; set; }
        public DbSet<LoaiMon> LoaiMon { get; set; }
        public DbSet<Thich> Thich { get; set; }
    
        public virtual int usp_BinhLuanMonAn(Nullable<int> monan, string nguoidung, string noidung)
        {
            var monanParameter = monan.HasValue ?
                new ObjectParameter("monan", monan) :
                new ObjectParameter("monan", typeof(int));
    
            var nguoidungParameter = nguoidung != null ?
                new ObjectParameter("nguoidung", nguoidung) :
                new ObjectParameter("nguoidung", typeof(string));
    
            var noidungParameter = noidung != null ?
                new ObjectParameter("noidung", noidung) :
                new ObjectParameter("noidung", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_BinhLuanMonAn", monanParameter, nguoidungParameter, noidungParameter);
        }
    
        public virtual ObjectResult<usp_LietKeBinhLuanMonAn_Result> usp_LietKeBinhLuanMonAn(Nullable<int> monan)
        {
            var monanParameter = monan.HasValue ?
                new ObjectParameter("monan", monan) :
                new ObjectParameter("monan", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_LietKeBinhLuanMonAn_Result>("usp_LietKeBinhLuanMonAn", monanParameter);
        }
    
        public virtual int usp_ThichMonAn(string manguoidung, Nullable<int> mamon)
        {
            var manguoidungParameter = manguoidung != null ?
                new ObjectParameter("manguoidung", manguoidung) :
                new ObjectParameter("manguoidung", typeof(string));
    
            var mamonParameter = mamon.HasValue ?
                new ObjectParameter("mamon", mamon) :
                new ObjectParameter("mamon", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ThichMonAn", manguoidungParameter, mamonParameter);
        }
    
        public virtual ObjectResult<usp_TimKiemMonAn_Result> usp_TimKiemMonAn(string tT, Nullable<int> row, Nullable<int> count)
        {
            var tTParameter = tT != null ?
                new ObjectParameter("TT", tT) :
                new ObjectParameter("TT", typeof(string));
    
            var rowParameter = row.HasValue ?
                new ObjectParameter("row", row) :
                new ObjectParameter("row", typeof(int));
    
            var countParameter = count.HasValue ?
                new ObjectParameter("count", count) :
                new ObjectParameter("count", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_TimKiemMonAn_Result>("usp_TimKiemMonAn", tTParameter, rowParameter, countParameter);
        }
    
        public virtual ObjectResult<usp_TimKiemNguoiDung_Result> usp_TimKiemNguoiDung(string tT, Nullable<int> row, Nullable<int> count)
        {
            var tTParameter = tT != null ?
                new ObjectParameter("TT", tT) :
                new ObjectParameter("TT", typeof(string));
    
            var rowParameter = row.HasValue ?
                new ObjectParameter("row", row) :
                new ObjectParameter("row", typeof(int));
    
            var countParameter = count.HasValue ?
                new ObjectParameter("count", count) :
                new ObjectParameter("count", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_TimKiemNguoiDung_Result>("usp_TimKiemNguoiDung", tTParameter, rowParameter, countParameter);
        }
    
        public virtual ObjectResult<usp_TopDauBep_Result> usp_TopDauBep()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_TopDauBep_Result>("usp_TopDauBep");
        }
    
        public virtual ObjectResult<usp_TopMonAnCuaDauBep_Result> usp_TopMonAnCuaDauBep(string madaubep, Nullable<int> count)
        {
            var madaubepParameter = madaubep != null ?
                new ObjectParameter("madaubep", madaubep) :
                new ObjectParameter("madaubep", typeof(string));
    
            var countParameter = count.HasValue ?
                new ObjectParameter("count", count) :
                new ObjectParameter("count", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_TopMonAnCuaDauBep_Result>("usp_TopMonAnCuaDauBep", madaubepParameter, countParameter);
        }
    
        public virtual ObjectResult<usp_TopMonAnThich_Result> usp_TopMonAnThich(Nullable<int> count)
        {
            var countParameter = count.HasValue ?
                new ObjectParameter("count", count) :
                new ObjectParameter("count", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_TopMonAnThich_Result>("usp_TopMonAnThich", countParameter);
        }
    }
}
