//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiDung
    {
        public string MaNguoiDung { get; set; }
        public string Ho { get; set; }
        public string Ten { get; set; }
        public string Hinh { get; set; }
        public string DiaChi { get; set; }
    }
}
